name: tqdne
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - h5py=3.10.0
  - jupyterlab=4.1.1
  - jupytext=1.16.1
  - matplotlib=3.8.2
  - ml-collections=0.1.1
  - obspy=1.4.0
  - diffusers=0.26.3
  - python=3.11.7
  - python-dotenv=1.0.1
  - pytorch::pytorch>=2.1
  - pytorch-cuda=11.8
  - torchvision>=0.17
  - pytorch-lightning>=2.0.0
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - tox=4.12.1
  - seaborn=0.13.2
  - wandb=0.16.3
  - librosa=0.10.1
  - pip=24.0
  - pip:
      - -e .